### Create Record
POST http://localhost:8080/api/v1/customers
Content-Type: application/json

{
  "name": "Tendulkar INC",
  "email": "something@someone.id"
}

### Get all records
GET http://localhost:8080/api/v1/customers

### Get single
GET http://localhost:8080/api/v1/customers/1


### Create Product
POST http://localhost:8080/api/v1/api/products
Content-Type: application/json

{
  "name": "Product 1",
  "description": "Product 1 Description",
  "price": 1000.99,
  "category": "Category 1"
}

### Fetch all products
GET http://localhost:8080/api/v1/api/products