# Start by building the application.
FROM golang:1.22 as builder

WORKDIR /go/src/app

# Copy the Go Modules manifests and download the dependencies
COPY consumer/go.mod consumer/go.sum ./
RUN go mod download

# Copy the rest of the source code
COPY ./consumer .

# Build the consumer binary statically.
# Enable CGO to build a fully static binary which is useful for a scratch container.
RUN CGO_ENABLED=0 go build -o /go/bin/consumer

# Now create a smaller image without Go installed.
# You can use scratch if you don't need anything else in the filesystem.
FROM scratch

# Import the compiled binary from the builder stage.
COPY --from=builder /go/bin/consumer /consumer

# Run the consumer binary.
ENTRYPOINT ["/consumer"]
